import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/app/providers/theme-provider";
import SmoothScroll from "@/lib/smooth-scroll";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chadcn UI Playground",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothScroll>{children}</SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
